import type { Metadata,Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


export const viewport: Viewport = {
  themeColor: '#colorHere',
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Knet Technologies",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
  manifest: "/site.webmanifest",
  themeColor: "#000000",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
  },
  viewport: "width=device-width, initial-scale=1",
  keywords: "Knet Technologies, Knet, Technologies, Web Development, Software Development",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
